//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Service.ConexionWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConexionWS.ConexionSQLSoap")]
    public interface ConexionSQLSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento correo del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        Web.Service.ConexionWS.LoginResponse Login(Web.Service.ConexionWS.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<Web.Service.ConexionWS.LoginResponse> LoginAsync(Web.Service.ConexionWS.LoginRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public Web.Service.ConexionWS.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(Web.Service.ConexionWS.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string correo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contrasenia;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string correo, string contrasenia) {
            this.correo = correo;
            this.contrasenia = contrasenia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public Web.Service.ConexionWS.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(Web.Service.ConexionWS.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(bool LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ConexionSQLSoapChannel : Web.Service.ConexionWS.ConexionSQLSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConexionSQLSoapClient : System.ServiceModel.ClientBase<Web.Service.ConexionWS.ConexionSQLSoap>, Web.Service.ConexionWS.ConexionSQLSoap {
        
        public ConexionSQLSoapClient() {
        }
        
        public ConexionSQLSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConexionSQLSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConexionSQLSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConexionSQLSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web.Service.ConexionWS.LoginResponse Web.Service.ConexionWS.ConexionSQLSoap.Login(Web.Service.ConexionWS.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public bool Login(string correo, string contrasenia) {
            Web.Service.ConexionWS.LoginRequest inValue = new Web.Service.ConexionWS.LoginRequest();
            inValue.Body = new Web.Service.ConexionWS.LoginRequestBody();
            inValue.Body.correo = correo;
            inValue.Body.contrasenia = contrasenia;
            Web.Service.ConexionWS.LoginResponse retVal = ((Web.Service.ConexionWS.ConexionSQLSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Web.Service.ConexionWS.LoginResponse> Web.Service.ConexionWS.ConexionSQLSoap.LoginAsync(Web.Service.ConexionWS.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<Web.Service.ConexionWS.LoginResponse> LoginAsync(string correo, string contrasenia) {
            Web.Service.ConexionWS.LoginRequest inValue = new Web.Service.ConexionWS.LoginRequest();
            inValue.Body = new Web.Service.ConexionWS.LoginRequestBody();
            inValue.Body.correo = correo;
            inValue.Body.contrasenia = contrasenia;
            return ((Web.Service.ConexionWS.ConexionSQLSoap)(this)).LoginAsync(inValue);
        }
    }
}
