//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService.Sql {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Sql.SQLSoap")]
    public interface SQLSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Login(string correo, string contrasenia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> LoginAsync(string correo, string contrasenia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Mostrar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Mostrar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Mostrar", ReplyAction="*")]
        System.Threading.Tasks.Task MostrarAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SQLSoapChannel : WebService.Sql.SQLSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SQLSoapClient : System.ServiceModel.ClientBase<WebService.Sql.SQLSoap>, WebService.Sql.SQLSoap {
        
        public SQLSoapClient() {
        }
        
        public SQLSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SQLSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SQLSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SQLSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Login(string correo, string contrasenia) {
            return base.Channel.Login(correo, contrasenia);
        }
        
        public System.Threading.Tasks.Task<bool> LoginAsync(string correo, string contrasenia) {
            return base.Channel.LoginAsync(correo, contrasenia);
        }
        
        public void Mostrar() {
            base.Channel.Mostrar();
        }
        
        public System.Threading.Tasks.Task MostrarAsync() {
            return base.Channel.MostrarAsync();
        }
    }
}
