//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FemsJubService.SQL {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SQL.SQLSoap")]
    public interface SQLSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Login(string correo, string contrasenia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> LoginAsync(string correo, string contrasenia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Mostrar_aprobados", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Mostrar_aprobados();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Mostrar_aprobados", ReplyAction="*")]
        System.Threading.Tasks.Task Mostrar_aprobadosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Mostrar_PorAutorizar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Mostrar_PorAutorizar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Mostrar_PorAutorizar", ReplyAction="*")]
        System.Threading.Tasks.Task Mostrar_PorAutorizarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Eliminar(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar", ReplyAction="*")]
        System.Threading.Tasks.Task EliminarAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Autorizar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Autorizar(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Autorizar", ReplyAction="*")]
        System.Threading.Tasks.Task AutorizarAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Crear_Usuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Crear_Usuario(string nombre, string apellidop, string apellidom, string correo, string contrasenia, string foto, string telefono, string direccion, string tusuario, string estatus, string pais, string estado, string municipio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Crear_Usuario", ReplyAction="*")]
        System.Threading.Tasks.Task Crear_UsuarioAsync(string nombre, string apellidop, string apellidom, string correo, string contrasenia, string foto, string telefono, string direccion, string tusuario, string estatus, string pais, string estado, string municipio);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SQLSoapChannel : FemsJubService.SQL.SQLSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SQLSoapClient : System.ServiceModel.ClientBase<FemsJubService.SQL.SQLSoap>, FemsJubService.SQL.SQLSoap {
        
        public SQLSoapClient() {
        }
        
        public SQLSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SQLSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SQLSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SQLSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Login(string correo, string contrasenia) {
            return base.Channel.Login(correo, contrasenia);
        }
        
        public System.Threading.Tasks.Task<bool> LoginAsync(string correo, string contrasenia) {
            return base.Channel.LoginAsync(correo, contrasenia);
        }
        
        public void Mostrar_aprobados() {
            base.Channel.Mostrar_aprobados();
        }
        
        public System.Threading.Tasks.Task Mostrar_aprobadosAsync() {
            return base.Channel.Mostrar_aprobadosAsync();
        }
        
        public void Mostrar_PorAutorizar() {
            base.Channel.Mostrar_PorAutorizar();
        }
        
        public System.Threading.Tasks.Task Mostrar_PorAutorizarAsync() {
            return base.Channel.Mostrar_PorAutorizarAsync();
        }
        
        public void Eliminar(int id) {
            base.Channel.Eliminar(id);
        }
        
        public System.Threading.Tasks.Task EliminarAsync(int id) {
            return base.Channel.EliminarAsync(id);
        }
        
        public void Autorizar(int id) {
            base.Channel.Autorizar(id);
        }
        
        public System.Threading.Tasks.Task AutorizarAsync(int id) {
            return base.Channel.AutorizarAsync(id);
        }
        
        public void Crear_Usuario(string nombre, string apellidop, string apellidom, string correo, string contrasenia, string foto, string telefono, string direccion, string tusuario, string estatus, string pais, string estado, string municipio) {
            base.Channel.Crear_Usuario(nombre, apellidop, apellidom, correo, contrasenia, foto, telefono, direccion, tusuario, estatus, pais, estado, municipio);
        }
        
        public System.Threading.Tasks.Task Crear_UsuarioAsync(string nombre, string apellidop, string apellidom, string correo, string contrasenia, string foto, string telefono, string direccion, string tusuario, string estatus, string pais, string estado, string municipio) {
            return base.Channel.Crear_UsuarioAsync(nombre, apellidop, apellidom, correo, contrasenia, foto, telefono, direccion, tusuario, estatus, pais, estado, municipio);
        }
    }
}
